on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemoeitan1111.azurecr.io
        username: ${{ secrets.acr_acrdemoeitan1111_username }}
        password: ${{ secrets.acr_acrdemoeitan1111_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemoeitan1111.azurecr.io/askdemoeitan:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemoeitan1111.azurecr.io/askdemoeitan:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_askdemoeitan_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ask-demoeitanba65 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ask-demoeitanba65`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ask-demoeitanba65
        container-registry-url: acrdemoeitan1111.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemoeitan1111_username }}
        container-registry-password: ${{ secrets.acr_acrdemoeitan1111_password }}
        secret-name: askdemoeitandockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ask-demoeitanba65
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          acrdemoeitan1111.azurecr.io/askdemoeitan:${{ github.sha }}
        imagepullsecrets: |
          askdemoeitandockerauth
